name: Deploy
on:
  push:
    branches:
      - devnet
jobs:
  deploy:
    name: Release
    runs-on: ubuntu-latest
    environment: devnet
    steps:
      - uses: actions/checkout@master
      - name: Downloading elys
        run: |
          URL=https://github.com/elys-network/elys/releases/download/v0.29.26/elysd-v0.29.26-linux-amd64
          wget $URL -O elysd
          chmod +x elysd
          ls
      #- name: Compile with Docker
      #    # build wasm files
      #    ./scripts/build.sh
      - name: Deploy
        run: |
            # helper functions
            extract_txhash() { awk -F 'txhash: ' '/txhash:/{print $2; exit}'; }
            extract_code_id() { awk -F 'key: code_id|value: ' '/key: code_id/ { getline; gsub(/"/, "", $2); print $2; exit }'; }
            extract_contract_address() { awk -F 'key: _contract_address|value: ' '/key: _contract_address/ { getline; gsub(/"/, "", $2); print $2; exit }'; }
            extract_account_number() { awk -F 'account_number: ' '/account_number:/ { gsub(/"/, "", $2); print $2 + 0; exit; }'; }
            extract_sequence() { awk -F 'sequence: ' '/sequence:/ { gsub(/"/, "", $2); print $2 + 0; exit; }'; }
            wait_for_tx() {
                local txhash=$1
                # loop until query tx cli does not fail
                while ! elysd q tx $txhash --node "$NODE" &> /dev/null; do
                    echo "Waiting for the transaction $txhash to be included in a block..."
                    sleep 0.5
                done
            }

            # environment variables
            NODE=https://rpc.devnet.elys.network:443
            NAME=mallorca

            # contract addresses enviroment variables

            ELYSD=./elysd

            # set elysd config
            $ELYSD config keyring-backend test
            $ELYSD config node $NODE
            $ELYSD config chain-id elysdevnet-1
            $ELYSD config broadcast-mode sync

            # save private keys to files
            echo "${{ secrets.PRIVATE_KEY_MALLORCA }}" > /tmp/private_key_mallorca.txt
            echo "${{ secrets.PASSPHRASE_MALLORCA }}" > /tmp/private_key_mallorca_2.txt
      - name: Run tmate
        uses: mxschmitt/action-tmate@v2
