name: Pipeline
on:
  push:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Build 
        run: |
          cargo build --verbose
        working-directory: .
  test:
    needs: build
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: test 
        run: |
          cargo test --verbose
        working-directory: .
  deploy:
    name: deploy in devnet
    if:  github.ref == 'refs/heads/devnet'
    uses: fenriz07/binding-workflow/.github/workflows/deploy.yml@devnet
    #with:
    #  node: https://rpc.devnet.elys.network:443
    #  chainID: elysdevnet-1 
    #  from: mallorca  
    #  fs_contract_addrs: x 
    #  ts_contract_addrs: x 
    #  ah_contract_addrs: x   
    
    #secrets:
    #  PRIVATE_KEY: ${{ secrets.envPAT }}
    #  PASSPHRASE: ${{ secrets.envPAT }}