name: Pipeline
on:
  push:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Build 
        run: |
          echo ${{ github.ref }}
          cargo build --verbose
        working-directory: .
  test:
    needs: build
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: test 
        run: |
          cargo test --verbose
        working-directory: .
  deploy:
    name: deploy in devnet
    if:  github.base.ref == 'devnet'
    uses: fenriz07/binding-workflow/.github/workflows/deploy.yml@devnet